Fixed deploy-aws-eks.yml

diff --git a/.github/workflows/deploy-aws-eks.yml b/.github/workflows/deploy-aws-eks.yml
--- a/.github/workflows/deploy-aws-eks.yml
+++ b/.github/workflows/deploy-aws-eks.yml
@@ -239,22 +239,17 @@ jobs:
         id: tf-plan
         run: |
           cd terraform
-          set +e
-          terraform plan -detailed-exitcode -no-color -out=tfplan 2>&1 | tee tfplan.txt
-          export exitcode=${PIPESTATUS[0]}
-          set -e
+          terraform plan -detailed-exitcode -no-color -out=tfplan \
+          -var="db_password=" \
+          || export exitcode=$?
           
           echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
           
           if [ $exitcode -eq 1 ]; then
-            echo "Terraform Plan Failed!"
-            exit 1
-          elif [ $exitcode -eq 0 ]; then
-            echo "No changes detected"
-            exit 0
+          echo "Terraform Plan Failed!"
+          exit 1
           else
-            echo "Changes detected"
-            exit 0
+          exit 0
           fi
 
       - name: Upload Terraform Plan
